services:

  nginx:
    build: images/nginx/
    # image: grcote7/servers-in-docker:server_nginx
    volumes:
      # - nginx_conf:/etc/nginx/
      - ./php:/www
    ports:
      - "80:80"
      - "81:81"

  php:
    build: images/php/
    # image: grcote7/servers-in-docker:server_php
    volumes:
      - ./php:/www

  node:
    build: images/node/
    # image: grcote7/servers-in-docker:server_node
    volumes:
      - ./nodejs:/www

# volumes:

#   nginx_conf:
